semi: true
trailingComma: es5
singleQuote: true
printWidth: 120
tabWidth: 4
useTabs: false
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always

overrides:
    - files: '*.md'
      options:
          printWidth: 80
          proseWrap: always
