import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import NavigationBar from '@/components/NavigationBar';
import { RootStoreProvider } from '@/providers/RootStoreProvider';

import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
            >
                <RootStoreProvider>
                    <div className={`flex flex-col min-h-screen bg-neutral-50 dark:bg-neutral-900`}>
                        <NavigationBar className="sticky top-0 z-50" element="header" />
                        <main className="flex flex-col flex-1 gap-4 px-[20px] lg:px-0 overflow-x-hidden w-full max-w-3xl self-center box-border">
                            {children}
                        </main>
                    </div>
                </RootStoreProvider>
            </body>
        </html>
    );
}
